import * as shared from '../shared.mjs'
import { sources } from './sources.mjs'
const { signals_railway_line, loading_gauges, track_classes, knownStyles, defaultDate, themeSwitch, colors, font, turntable_casing_width, trainProtectionColor, railway_casing_add, bridge_casing_add, abandoned_dasharray, disused_dasharray, razed_dasharray, construction_dasharray, proposed_dasharray, present_dasharray, train_protection_construction_dasharray, turboColorMap, speedColor, speedHoverColor, electrification_construction_dashes, electrification_proposed_dashes, color_no, color_delectrified, color_lt750v_dc, color_750v_dc, color_gt750v_lt1kv_dc, color_1kv_dc, color_gt1kv_lt1500v_dc, color_1500v_dc, color_gt1500v_lt3kv_dc, color_3kv_dc, color_gt3kv_dc, color_lt15kv_ac, color_gte15kv_lt25kv_ac, color_gte25kv_ac, color_15kv_16_67hz, color_15kv_16_7hz, color_25kv_50hz, color_25kv_60hz, color_12kv_25hz, color_12_5kv_60hz, color_20kv_50hz, color_20kv_60hz, electrificationVoltageFrequencyColor, electrificationVoltageMaximumCurrentColor, electrificationPowerColor, gauge_construction_dashes, dual_construction_dashes, multi_construction_dashes, gauge_dual_gauge_dashes, gauge_multi_gauge_dashes, color_gauge_0064, color_gauge_0089, color_gauge_0127, color_gauge_0184, color_gauge_0190, color_gauge_0260, color_gauge_0381, color_gauge_0500, color_gauge_0597, color_gauge_0600, color_gauge_0610, color_gauge_0700, color_gauge_0750, color_gauge_0760, color_gauge_0762, color_gauge_0785, color_gauge_0800, color_gauge_0891, color_gauge_0900, color_gauge_0914, color_gauge_0950, color_gauge_1000, color_gauge_1009, color_gauge_1050, color_gauge_1067, color_gauge_1100, color_gauge_1200, color_gauge_1372, color_gauge_1422, color_gauge_1432, color_gauge_1435, color_gauge_1440, color_gauge_1445, color_gauge_1450, color_gauge_1458, color_gauge_1495, color_gauge_1520, color_gauge_1522, color_gauge_1524, color_gauge_1581, color_gauge_1588, color_gauge_1600, color_gauge_1668, color_gauge_1676, color_gauge_1700, color_gauge_1800, color_gauge_1880, color_gauge_2000, color_gauge_miniature, color_gauge_monorail, color_gauge_broad, color_gauge_narrow, color_gauge_standard, color_gauge_unknown, gaugeColor, loadingGaugeFillColor, trackClassFillColor, searchResults, railwayLine, historicalRailwayLine, railwayKmText, preferredDirectionLayer, imageLayerWithOutline, hillshade, route, routeText, routeStops, DATA_MAX_ZOOM, capSourcesForDataMaxZoom, capLayersForDataMaxZoom, makeStyle } = shared
export const electrification_textsLayers = [
  routeText,
  {
      id: 'electrification_catenary_mast',
      type: 'symbol',
      minzoom: 14,
      source: 'openrailwaymap_electrification',
      'source-layer': 'electrification_catenary',
      filter: ['==', ['get', 'feature'], 'mast'],
      paint: {
        'icon-color': colors.catenary,
        'icon-halo-width': 2,
        'icon-halo-color': ['case',
          ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo,
          colors.halo,
        ],
      },
      layout: {
        'icon-image': ['case',
          ['==', ['get', 'transition'], true], 'sdf:general/catenary-mast-transition',
          'sdf:general/catenary-mast',
        ],
        'icon-overlap': 'always',
        'icon-size': ['interpolate', ['exponential', 1.2], ['zoom'],
          14, 0.5,
          15, 0.75,
          17, 1.0,
        ],
      },
    },
  {
      id: 'electrification_catenary_mast_text',
      type: 'symbol',
      minzoom: 17,
      source: 'openrailwaymap_electrification',
      'source-layer': 'electrification_catenary',
      filter: ['all',
        ['==', ['get', 'feature'], 'mast'],
        ['!=', ['get', 'ref'], null],
      ],
      paint: {
        'text-color': colors.catenary,
        'text-halo-color': ['case',
          ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo,
          colors.halo,
        ],
        'text-halo-width': 2,
      },
      layout: {
        'text-field': '{ref}',
        'text-font': font.bold,
        'text-size': 11,
        'text-padding': 6,
        'text-max-width': 5,
        'text-offset': [0, 1],
      },
    },
  {
      id: 'electrification_catenary_portal',
      type: 'line',
      minzoom: 14,
      source: 'openrailwaymap_electrification',
      'source-layer': 'electrification_catenary',
      filter: ['==', ['get', 'feature'], 'portal'],
      paint: {
        'line-color': ['case',
          ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo,
          colors.catenary,
        ],
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'],
          14, 1.5,
          15, 2.0,
        ],
      },
    },
  {
      id: 'electrification_signals_direction',
      type: 'symbol',
      minzoom: 13,
      source: 'openrailwaymap_electrification',
      'source-layer': 'electrification_signals',
      filter: ['all',
        ['!=', ['get', 'azimuth'], null],
        ['!=', ['get', 'feature'], ''],
      ],
      paint: {
        'icon-color': colors.signals.direction,
        'icon-halo-color': ['case',
          ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo,
          colors.halo,
        ],
        'icon-halo-width': 2.0,
        'icon-halo-blur': 1.0,
        'icon-opacity': ['interpolate', ['linear'], ['zoom'],
          15, 0.85,
          16, 0.7,
        ],
      },
      layout: {
        'icon-overlap': 'always',
        'icon-image': ["step", ["zoom"],
          ['case',
            ['coalesce', ['get', 'direction_both'], false], 'sdf:general/signal-direction-both',
            'sdf:general/signal-direction',
          ],
          16, ['case',
            ['coalesce', ['get', 'direction_both'], false], 'sdf:general/signal-direction-large-both',
            'sdf:general/signal-direction-large',
          ],
        ],
        'icon-anchor': ['case',
          ['coalesce', ['get', 'direction_both'], false], 'center',
          'top',
        ],
        'icon-rotate': ['get', 'azimuth'],
        'icon-keep-upright': true,
        'icon-rotation-alignment': 'map',
      },
    },
  ...imageLayerWithOutline(
      'electrification_signals',
      ['get', 'feature'],
      {
        type: 'symbol',
        minzoom: 13,
        source: 'openrailwaymap_electrification',
        'source-layer': 'electrification_signals',
        paint: {
          'text-color': colors.text.main,
          'text-halo-color': ['case',
            ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo,
            colors.halo
          ],
          'text-halo-width': 1.5,
          'text-halo-blur': 1,
        },
        layout: {
          'symbol-z-order': 'source',
          'icon-overlap': 'always',
          'text-field': '{ref}',
          'text-font': font.regular,
          'text-size': 9,
          'text-optional': true,
          'text-anchor': 'top',
          'text-offset': ['literal', [0, 1.5]],
        },
      },
    ),
  {
      id: `electrification_signals_text`,
      type: 'symbol',
      minzoom: 16,
      source: 'openrailwaymap_electrification',
      'source-layer': 'electrification_signals',
      filter: ['any',
        ['!=', ['get', 'ref'], null],
        ['!=', ['get', 'caption'], null],
      ],
      paint: {
        'text-color': colors.text.main,
        'text-halo-color': ['case',
          ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo,
          colors.halo
        ],
        'text-halo-width': 1.5,
        'text-halo-blur': 1,
      },
      layout: {
        'text-field': ['format',
          ['get', 'ref'], {},
          ['case', ['all', ['!=', ['get', 'ref'], null], ['!=', ['get', 'caption'], null]], '\n', ''], {},
          ['case', ['==', ['get', 'caption'], null], '', ['get', 'caption']], {'text-font': ['literal', font.italic]},
        ],
        'text-font': font.regular,
        'text-size': 9,
        'text-anchor': 'top',
        'text-offset': ['interpolate', ['linear'],
          // 2 pixel spacing under icon
          ['/', ['+', ['get', 'offset'], 2], 9],
          0, ['literal', [0, 0]],
          20, ['literal', [0, 20]],
        ],
      },
    },
  {
      id: `electrification_symbols`,
      type: 'symbol',
      minzoom: 13,
      source: 'openrailwaymap_electrification',
      'source-layer': 'electrification_railway_symbols',
      paint: {
        'icon-color': colors.styles.standard.symbols,
        'icon-halo-color': ['case',
          ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo,
          colors.halo,
        ],
        'icon-halo-blur': ['case',
          ['boolean', ['feature-state', 'hover'], false], 1.0,
          0.0,
        ],
        'icon-halo-width': ['case',
          ['boolean', ['feature-state', 'hover'], false], 3.0,
          2.0,
        ],
        'text-color': colors.styles.standard.symbols,
        'text-halo-color': ['case',
          ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo,
          colors.halo,
        ],
        'text-halo-width': 2,
      },
      layout: {
        'symbol-z-order': 'source',
        'icon-overlap': 'always',
        'icon-image': ['concat', 'sdf:', ['get', 'feature']],
        'text-field': ['coalesce', ['get', 'ref'], ''],
        'text-font': font.regular,
        'text-size': 11,
        'text-padding': 15,
        'text-offset': [0, 1.5],
        'text-optional': true,
      },
    }
]
