import * as shared from '../shared.mjs'
import { sources } from './sources.mjs'
const {
  signals_railway_line,
  loading_gauges,
  track_classes,
  knownStyles,
  defaultDate,
  themeSwitch,
  colors,
  font,
  turntable_casing_width,
  trainProtectionColor,
  railway_casing_add,
  bridge_casing_add,
  abandoned_dasharray,
  disused_dasharray,
  razed_dasharray,
  construction_dasharray,
  proposed_dasharray,
  present_dasharray,
  train_protection_construction_dasharray,
  turboColorMap,
  speedColor,
  speedHoverColor,
  electrification_construction_dashes,
  electrification_proposed_dashes,
  color_no,
  color_delectrified,
  color_lt750v_dc,
  color_750v_dc,
  color_gt750v_lt1kv_dc,
  color_1kv_dc,
  color_gt1kv_lt1500v_dc,
  color_1500v_dc,
  color_gt1500v_lt3kv_dc,
  color_3kv_dc,
  color_gt3kv_dc,
  color_lt15kv_ac,
  color_gte15kv_lt25kv_ac,
  color_gte25kv_ac,
  color_15kv_16_67hz,
  color_15kv_16_7hz,
  color_25kv_50hz,
  color_25kv_60hz,
  color_12kv_25hz,
  color_12_5kv_60hz,
  color_20kv_50hz,
  color_20kv_60hz,
  electrificationVoltageFrequencyColor,
  electrificationVoltageMaximumCurrentColor,
  electrificationPowerColor,
  gauge_construction_dashes,
  dual_construction_dashes,
  multi_construction_dashes,
  gauge_dual_gauge_dashes,
  gauge_multi_gauge_dashes,
  color_gauge_0064,
  color_gauge_0089,
  color_gauge_0127,
  color_gauge_0184,
  color_gauge_0190,
  color_gauge_0260,
  color_gauge_0381,
  color_gauge_0500,
  color_gauge_0597,
  color_gauge_0600,
  color_gauge_0610,
  color_gauge_0700,
  color_gauge_0750,
  color_gauge_0760,
  color_gauge_0762,
  color_gauge_0785,
  color_gauge_0800,
  color_gauge_0891,
  color_gauge_0900,
  color_gauge_0914,
  color_gauge_0950,
  color_gauge_1000,
  color_gauge_1009,
  color_gauge_1050,
  color_gauge_1067,
  color_gauge_1100,
  color_gauge_1200,
  color_gauge_1372,
  color_gauge_1422,
  color_gauge_1432,
  color_gauge_1435,
  color_gauge_1440,
  color_gauge_1445,
  color_gauge_1450,
  color_gauge_1458,
  color_gauge_1495,
  color_gauge_1520,
  color_gauge_1522,
  color_gauge_1524,
  color_gauge_1581,
  color_gauge_1588,
  color_gauge_1600,
  color_gauge_1668,
  color_gauge_1676,
  color_gauge_1700,
  color_gauge_1800,
  color_gauge_1880,
  color_gauge_2000,
  color_gauge_miniature,
  color_gauge_monorail,
  color_gauge_broad,
  color_gauge_narrow,
  color_gauge_standard,
  color_gauge_unknown,
  gaugeColor,
  loadingGaugeFillColor,
  trackClassFillColor,
  searchResults,
  railwayLine,
  historicalRailwayLine,
  railwayKmText,
  preferredDirectionLayer,
  imageLayerWithOutline,
  hillshade,
  route,
  routeText,
  routeStops,
  DATA_MAX_ZOOM,
  capSourcesForDataMaxZoom,
  capLayersForDataMaxZoom,
  makeStyle,
} = shared
export const operator_textsLayers = [
  routeText,
  {
    id: 'railway_text_stations_low1',
    type: 'symbol',
    minzoom: 4,
    maxzoom: 5,
    source: 'standard_railway_text_stations_low',
    'source-layer': 'standard_railway_text_stations_low',
    filter: ['all', ['!=', ['get', 'operator'], null], ['>', ['get', 'discr_iso'], 38899]],
    paint: {
      'icon-color': ['get', 'operator_color'],
      'icon-halo-width': 1,
      'icon-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
    },
    layout: {
      'symbol-z-order': 'source',
      'icon-image': 'sdf:general/station-small',
      'icon-overlap': 'always',
    },
  },
  {
    id: 'railway_text_stations_low2',
    type: 'symbol',
    minzoom: 5,
    maxzoom: 7,
    source: 'standard_railway_text_stations_low',
    'source-layer': 'standard_railway_text_stations_low',
    filter: [
      'all',
      ['!=', ['get', 'operator'], null],
      [
        '>',
        ['get', 'discr_iso'],
        [
          'step',
          ['zoom'],
          22906, // z5
          6,
          11408, // z6
        ],
      ],
    ],
    paint: {
      'text-color': ['get', 'operator_color'],
      'text-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'text-halo-width': 1.5,
      'icon-color': ['get', 'operator_color'],
      'icon-halo-width': 1.5,
      'icon-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
    },
    layout: {
      'symbol-z-order': 'source',
      'icon-image': ['image', ['concat', 'sdf:general/station-', ['get', 'station_size']]],
      'icon-overlap': 'always',
      'text-field': [
        'match',
        ['global-state', 'stationLowZoomLabel'],
        'label',
        ['get', 'label'],
        'name',
        ['get', 'localized_name'],
        '',
      ],
      'text-font': font.bold,
      'text-size': 11,
      'text-padding': 10,
      'text-max-width': 8,
      'text-optional': true,
      'text-variable-anchor': ['top', 'bottom', 'left', 'right'],
    },
  },
  {
    id: 'railway_text_stations_med',
    type: 'symbol',
    minzoom: 7,
    maxzoom: 8,
    source: 'standard_railway_text_stations_med',
    'source-layer': 'standard_railway_text_stations_med',
    filter: ['!=', ['get', 'operator'], null],
    paint: {
      'text-color': ['get', 'operator_color'],
      'text-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'text-halo-width': 2,
      'icon-color': ['get', 'operator_color'],
      'icon-halo-width': 2,
      'icon-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
    },
    layout: {
      'symbol-z-order': 'source',
      'icon-image': ['image', ['concat', 'sdf:general/station-', ['get', 'station_size']]],
      'icon-overlap': 'always',
      'text-field': [
        'match',
        ['get', 'station_size'],
        'small',
        '',
        [
          'match',
          ['global-state', 'stationLowZoomLabel'],
          'label',
          ['get', 'label'],
          'name',
          ['get', 'localized_name'],
          '',
        ],
      ],
      'text-font': font.bold,
      'text-size': 11,
      'text-padding': 10,
      'text-max-width': 8,
      'text-optional': true,
      'text-variable-anchor': ['top', 'bottom', 'left', 'right'],
    },
  },
  {
    id: 'railway_text_stations',
    type: 'symbol',
    minzoom: 8,
    maxzoom: 13,
    source: 'openrailwaymap_standard',
    'source-layer': 'standard_railway_text_stations',
    filter: [
      'step',
      ['zoom'],
      [
        'all',
        ['!=', ['get', 'operator'], null],
        ['==', ['get', 'state'], 'present'],
        ['any', ['==', ['get', 'feature'], 'station'], ['==', ['get', 'feature'], 'yard']],
        ['!=', ['get', 'station'], 'light_rail'],
        ['!=', ['get', 'station'], 'subway'],
        ['!=', ['get', 'station'], 'monorail'],
        ['!=', ['get', 'station'], 'funicular'],
      ],
      9,
      [
        'all',
        ['!=', ['get', 'operator'], null],
        ['==', ['get', 'state'], 'present'],
        [
          'any',
          ['==', ['get', 'feature'], 'station'],
          ['==', ['get', 'feature'], 'yard'],
          ['==', ['get', 'feature'], 'halt'],
        ],
        ['!=', ['get', 'station'], 'light_rail'],
        ['!=', ['get', 'station'], 'tram'],
        ['!=', ['get', 'station'], 'subway'],
        ['!=', ['get', 'station'], 'monorail'],
        ['!=', ['get', 'station'], 'funicular'],
      ],
      10,
      [
        'all',
        ['!=', ['get', 'operator'], null],
        ['!=', ['get', 'station'], 'tram'],
        ['!=', ['get', 'station'], 'funicular'],
        ['!=', ['get', 'station'], 'miniature'],
      ],
      11,
      [
        'all',
        ['!=', ['get', 'operator'], null],
        ['!=', ['get', 'station'], 'funicular'],
        ['!=', ['get', 'station'], 'miniature'],
      ],
    ],
    paint: {
      'text-color': ['get', 'operator_color'],
      'text-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'text-halo-width': 1.5,
      'icon-color': ['get', 'operator_color'],
      'icon-halo-width': 1.5,
      'icon-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
    },
    layout: {
      'symbol-z-order': 'source',
      'icon-image': [
        'image',
        [
          'concat',
          'sdf:general/station-',
          [
            'case',
            ['in', ['get', 'state'], ['literal', ['disused', 'abandoned', 'preserved', 'razed']]],
            'past',
            ['in', ['get', 'state'], ['literal', ['construction', 'proposed']]],
            'future',
            ['get', 'station_size'],
          ],
        ],
      ],
      'icon-overlap': 'always',
      'text-field': [
        'step',
        ['zoom'],
        [
          'match',
          ['global-state', 'stationLowZoomLabel'],
          'label',
          ['get', 'label'],
          'name',
          ['get', 'localized_name'],
          '',
        ],
        10,
        ['get', 'localized_name'],
        12,
        [
          'format',
          ['get', 'localized_name'],
          {},
          ['case', ['!=', ['get', 'name'], ['get', 'localized_name']], ['concat', '\n', ['get', 'name']], ''],
          {
            'text-font': ['literal', font.regular],
          },
        ],
      ],
      'text-font': [
        'case',
        ['in', ['get', 'state'], ['literal', ['construction', 'proposed']]],
        ['literal', font.italic],
        ['literal', font.bold],
      ],
      'text-size': 11,
      'text-padding': 10,
      'text-max-width': 8,
      'text-optional': true,
      'text-variable-anchor': ['top', 'bottom', 'left', 'right'],
    },
  },
  {
    id: 'railway_text_stations_high',
    type: 'symbol',
    minzoom: 13,
    source: 'openrailwaymap_standard',
    'source-layer': 'standard_railway_text_stations',
    filter: [
      'all',
      ['!=', ['get', 'operator'], null],
      ['!', ['in', ['get', 'feature'], ['literal', ['site', 'junction', 'spur_junction']]]],
      [
        'match',
        ['get', 'state'],
        'construction',
        ['global-state', 'showConstructionInfrastructure'],
        'proposed',
        ['global-state', 'showProposedInfrastructure'],
        'abandoned',
        ['global-state', 'showAbandonedInfrastructure'],
        'razed',
        ['global-state', 'showRazedInfrastructure'],
        true,
      ],
    ],
    paint: {
      'text-color': ['get', 'operator_color'],
      'text-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'text-halo-width': 1.5,
    },
    layout: {
      'symbol-z-order': 'source',
      'text-field': [
        'step',
        ['zoom'],
        [
          'format',
          ['get', 'localized_name'],
          {},
          ['case', ['!=', ['get', 'name'], ['get', 'localized_name']], ['concat', '\n', ['get', 'name']], ''],
          {
            'text-font': ['literal', font.regular],
          },
        ],
        15,
        [
          'format',
          ['get', 'localized_name'],
          {},
          ['case', ['>', ['coalesce', ['get', 'count'], 0], 1], ['concat', ' (', ['get', 'count'], ')'], ''],
          {},
          ['case', ['!=', ['get', 'name'], ['get', 'localized_name']], ['concat', '\n', ['get', 'name']], ''],
          {
            'text-font': ['literal', font.regular],
          },
        ],
      ],
      'text-font': [
        'case',
        ['in', ['get', 'state'], ['literal', ['construction', 'proposed']]],
        ['literal', font.italic],
        ['literal', font.bold],
      ],
      'text-variable-anchor': ['center', 'top', 'bottom', 'left', 'right'],
      'text-size': 11,
      'text-padding': 10,
      'text-max-width': 8,
    },
  },
  {
    id: 'railway_text_site_junction_high',
    type: 'symbol',
    minzoom: 13,
    source: 'openrailwaymap_standard',
    'source-layer': 'standard_railway_text_stations',
    filter: [
      'all',
      ['!=', ['get', 'operator'], null],
      ['in', ['get', 'feature'], ['literal', ['site', 'junction', 'spur_junction']]],
      [
        'match',
        ['get', 'state'],
        'construction',
        ['global-state', 'showConstructionInfrastructure'],
        'proposed',
        ['global-state', 'showProposedInfrastructure'],
        'abandoned',
        ['global-state', 'showAbandonedInfrastructure'],
        'razed',
        ['global-state', 'showRazedInfrastructure'],
        true,
      ],
    ],
    paint: {
      'text-color': ['get', 'operator_color'],
      'text-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'text-halo-width': 1.5,
      'icon-color': ['get', 'operator_color'],
      'icon-halo-width': 1.5,
      'icon-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
    },
    layout: {
      visibility: ['case', ['<', ['global-state', 'date'], defaultDate], 'none', 'visible'],
      'symbol-z-order': 'source',
      'icon-image': 'sdf:general/station-small',
      'icon-overlap': 'always',
      'text-field': [
        'step',
        ['zoom'],
        [
          'format',
          ['get', 'localized_name'],
          {},
          ['case', ['!=', ['get', 'name'], ['get', 'localized_name']], ['concat', '\n', ['get', 'name']], ''],
          {
            'text-font': ['literal', font.regular],
          },
        ],
        15,
        [
          'format',
          ['get', 'localized_name'],
          {},
          ['case', ['!=', ['get', 'name'], ['get', 'localized_name']], ['concat', '\n', ['get', 'name']], ''],
          {
            'text-font': ['literal', font.regular],
          },
        ],
      ],
      'text-font': [
        'case',
        ['in', ['get', 'state'], ['literal', ['construction', 'proposed']]],
        ['literal', font.italic],
        ['literal', font.bold],
      ],
      'text-variable-anchor': ['top', 'bottom', 'left', 'right'],
      'text-size': 11,
      'text-padding': 10,
      'text-max-width': 8,
    },
  },
  {
    id: 'signal_boxes_text_medium',
    type: 'symbol',
    minzoom: 12,
    maxzoom: 15,
    source: 'openrailwaymap_signals',
    'source-layer': 'signals_signal_boxes',
    filter: ['all', ['!=', ['get', 'operator'], null], ['!=', ['get', 'ref'], null]],
    paint: {
      'text-color': ['get', 'operator_color'],
      'text-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'text-halo-width': 1.5,
    },
    layout: {
      'text-field': '{ref}',
      'text-font': font.bold,
      'text-size': 11,
      'text-offset': ['literal', [0, 1]],
    },
  },
  {
    id: 'signal_boxes_text_high',
    type: 'symbol',
    minzoom: 15,
    source: 'openrailwaymap_signals',
    'source-layer': 'signals_signal_boxes',
    filter: ['all', ['!=', ['get', 'operator'], null], ['!=', ['get', 'name'], null]],
    paint: {
      'text-color': ['get', 'operator_color'],
      'text-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'text-halo-width': 1.5,
    },
    layout: {
      'text-field': '{name}',
      'text-font': font.bold,
      'text-size': 11,
    },
  },
  {
    id: `operator_symbols`,
    type: 'symbol',
    minzoom: 10,
    source: 'openrailwaymap_operator',
    'source-layer': 'operator_railway_symbols',
    paint: {
      'icon-color': colors.styles.standard.symbols,
      'icon-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'icon-halo-blur': ['case', ['boolean', ['feature-state', 'hover'], false], 1.0, 0.0],
      'icon-halo-width': ['case', ['boolean', ['feature-state', 'hover'], false], 3.0, 2.0],
      'text-color': colors.styles.standard.symbols,
      'text-halo-color': ['case', ['boolean', ['feature-state', 'hover'], false], colors.hover.textHalo, colors.halo],
      'text-halo-width': 2,
    },
    layout: {
      'symbol-z-order': 'source',
      'icon-overlap': 'always',
      'icon-image': ['concat', 'sdf:', ['get', 'feature']],
      'text-field': ['coalesce', ['get', 'ref'], ''],
      'text-font': font.regular,
      'text-size': 11,
      'text-padding': 15,
      'text-offset': [0, 1.5],
      'text-optional': true,
    },
  },
]
