import * as shared from '../shared.mjs'
import { sources } from './sources.mjs'
const { signals_railway_line, loading_gauges, track_classes, knownStyles, defaultDate, themeSwitch, colors, font, turntable_casing_width, trainProtectionColor, railway_casing_add, bridge_casing_add, abandoned_dasharray, disused_dasharray, razed_dasharray, construction_dasharray, proposed_dasharray, present_dasharray, train_protection_construction_dasharray, turboColorMap, speedColor, speedHoverColor, electrification_construction_dashes, electrification_proposed_dashes, color_no, color_delectrified, color_lt750v_dc, color_750v_dc, color_gt750v_lt1kv_dc, color_1kv_dc, color_gt1kv_lt1500v_dc, color_1500v_dc, color_gt1500v_lt3kv_dc, color_3kv_dc, color_gt3kv_dc, color_lt15kv_ac, color_gte15kv_lt25kv_ac, color_gte25kv_ac, color_15kv_16_67hz, color_15kv_16_7hz, color_25kv_50hz, color_25kv_60hz, color_12kv_25hz, color_12_5kv_60hz, color_20kv_50hz, color_20kv_60hz, electrificationVoltageFrequencyColor, electrificationVoltageMaximumCurrentColor, electrificationPowerColor, gauge_construction_dashes, dual_construction_dashes, multi_construction_dashes, gauge_dual_gauge_dashes, gauge_multi_gauge_dashes, color_gauge_0064, color_gauge_0089, color_gauge_0127, color_gauge_0184, color_gauge_0190, color_gauge_0260, color_gauge_0381, color_gauge_0500, color_gauge_0597, color_gauge_0600, color_gauge_0610, color_gauge_0700, color_gauge_0750, color_gauge_0760, color_gauge_0762, color_gauge_0785, color_gauge_0800, color_gauge_0891, color_gauge_0900, color_gauge_0914, color_gauge_0950, color_gauge_1000, color_gauge_1009, color_gauge_1050, color_gauge_1067, color_gauge_1100, color_gauge_1200, color_gauge_1372, color_gauge_1422, color_gauge_1432, color_gauge_1435, color_gauge_1440, color_gauge_1445, color_gauge_1450, color_gauge_1458, color_gauge_1495, color_gauge_1520, color_gauge_1522, color_gauge_1524, color_gauge_1581, color_gauge_1588, color_gauge_1600, color_gauge_1668, color_gauge_1676, color_gauge_1700, color_gauge_1800, color_gauge_1880, color_gauge_2000, color_gauge_miniature, color_gauge_monorail, color_gauge_broad, color_gauge_narrow, color_gauge_standard, color_gauge_unknown, gaugeColor, loadingGaugeFillColor, trackClassFillColor, searchResults, railwayLine, historicalRailwayLine, railwayKmText, preferredDirectionLayer, imageLayerWithOutline, hillshade, route, routeText, routeStops, DATA_MAX_ZOOM, capSourcesForDataMaxZoom, capLayersForDataMaxZoom, makeStyle } = shared
export const standardLinesLayers = [
  hillshade,
  ...railwayLine(
      ['step', ['zoom'],
        ['coalesce', ['get', 'ref'], ''],
        14,
        ['coalesce', ['get', 'standard_label'], ''],
      ],
      [
        {
          id: 'railway_line_main_low',
          minzoom: 0,
          maxzoom: 7,
          source: 'standard_railway_line_low',
          sourceLayer: 'standard_railway_line_low',
          states: {
            present: undefined,
          },
          filter: ['==', ['get', 'feature'], 'rail'],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            0, 0.5,
            7, 2,
          ],
          color: ['case',
            ['get', 'highspeed'], colors.styles.standard.highspeed,
            colors.styles.standard.main,
          ],
          hoverColor: ['case',
            ['get', 'highspeed'], colors.hover.alternative,
            colors.hover.main,
          ],
        },
        {
          id: 'railway_ferry_main_low',
          minzoom: 0,
          maxzoom: 7,
          source: 'standard_railway_line_low',
          sourceLayer: 'standard_railway_line_low',
          states: {
            present: undefined,
          },
          filter: ['==', ['get', 'feature'], 'ferry'],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            0, 0.5,
            7, 2,
          ],
          color: colors.styles.standard.ferry,
          hoverColor: colors.hover.main,
        },

        // Medium zooms
        // ensure that width interpolation matches low zooms

        {
          id: 'railway_line_main_med',
          minzoom: 7,
          maxzoom: 8,
          source: 'openrailwaymap_low',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['all',
            ['==', ['get', 'feature'], 'rail'],
            ['==', ['get', 'usage'], 'main'],
          ],
          width: 2,
          color: ['case',
            ['get', 'highspeed'], colors.styles.standard.highspeed,
            colors.styles.standard.main,
          ],
          hoverColor: ['case',
            ['get', 'highspeed'], colors.hover.alternative,
            colors.hover.main,
          ],
        },
        {
          id: 'railway_line_branch_med',
          minzoom: 7,
          maxzoom: 8,
          source: 'openrailwaymap_low',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['all',
            ['==', ['get', 'feature'], 'rail'],
            ['==', ['get', 'usage'], 'branch'],
          ],
          width: 2,
          color: colors.styles.standard.branch,
        },
        {
          id: 'railway_ferry_med',
          minzoom: 7,
          maxzoom: 8,
          source: 'openrailwaymap_low',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['==', ['get', 'feature'], 'ferry'],
          width: 2,
          color: colors.styles.standard.ferry,
        },

        // High zooms
        // ensure that width interpolation matches medium zooms
        {
          id: 'railway_line_razed',
          minzoom: 12,
          source: 'high',
          states: {
            razed: razed_dasharray,
          },
          filter: ['==', ['get', 'state'], 'razed'],
          width: 2,
          color: colors.styles.standard.razed,
        },
        {
          id: 'railway_line_abandoned',
          minzoom: 12,
          source: 'high',
          states: {
            abandoned: abandoned_dasharray,
          },
          filter: ['==', ['get', 'state'], 'abandoned'],
          width: 2,
          color: colors.styles.standard.abandoned,
        },
        {
          id: 'railway_line_miniature',
          minzoom: 12,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['==', ['get', 'feature'], 'miniature'],
          width: 2,
          color: colors.styles.standard.miniature,
        },
        {
          id: 'railway_line_funicular',
          minzoom: 12,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['==', ['get', 'feature'], 'funicular'],
          width: 2,
          color: colors.styles.standard.funicular,
        },
        {
          id: 'railway_line_disused',
          minzoom: 11,
          source: 'high',
          states: {
            disused: disused_dasharray,
          },
          width: 1.5,
          color: colors.styles.standard.disused,
        },
        {
          id: 'railway_line_narrow_gauge',
          minzoom: 10,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['all',
            ['==', ['get', 'feature'], 'narrow_gauge'],
            ['!',
              // Covered by industrial case
              ['==', ['get', 'usage'], 'industrial'],
            ],
          ],
          width: 2,
          color: colors.styles.standard.narrowGauge,
        },
        {
          id: 'railway_line_service',
          minzoom: 10,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['all',
            ['==', ['get', 'feature'], 'rail'],
            ['==', ['get', 'usage'], null],
          ],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            8, ['match', ['get', 'service'],
              'yard', 1,
              1.5,
            ],
            15, ['match', ['get', 'service'],
              'yard', 1,
              1.5,
            ],
            16, 2,
          ],
          color: ['match', ['get', 'service'],
            'spur', colors.styles.standard.spur,
            'siding', colors.styles.standard.siding,
            'yard', colors.styles.standard.yard,
            'crossover', colors.styles.standard.crossover,
            colors.styles.standard.unknown,
          ],
        },
        {
          id: 'railway_line_light_rail',
          minzoom: 9,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['any',
            ['==', ['get', 'feature'], 'subway'],
            ['==', ['get', 'feature'], 'tram'],
            ['==', ['get', 'feature'], 'light_rail'],
            ['==', ['get', 'feature'], 'monorail'],
          ],
          width: 2,
          color: ['match', ['get', 'feature'],
            'light_rail', colors.styles.standard.light_rail,
            'monorail', colors.styles.standard.monorail,
            'subway', colors.styles.standard.subway,
            'tram', colors.styles.standard.tram,
            colors.styles.standard.unknown,
          ],
        },
        {
          id: 'railway_line_test_military',
          minzoom: 9,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['all',
            ['==', ['get', 'feature'], 'rail'],
            ['any',
              ['==', ['get', 'usage'], 'test'],
              ['==', ['get', 'usage'], 'military'],
            ],
          ],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            8, 1.5,
            14, 1.5,
            16, 2,
          ],
          color: ['match', ['get', 'usage'],
            'test', colors.styles.standard.test,
            'military', colors.styles.standard.military,
            colors.styles.standard.unknown,
          ],
        },
        {
          id: 'railway_line_tourism',
          minzoom: 9,
          source: 'high',
          states: {
            present: undefined,
            preserved: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['any',
            ['==', ['get', 'usage'], 'tourism'],
            ['==', ['get', 'state'], 'preserved'],
          ],
          width: 2,
          color: colors.styles.standard.tourism,
        },
        {
          id: 'railway_line_industrial',
          minzoom: 9,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['all',
            ['==', ['get', 'usage'], 'industrial'],
            ['any',
              ['==', ['get', 'feature'], 'rail'],
              ['==', ['get', 'feature'], 'narrow_gauge'],
            ],
          ],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            8, 1.5,
            14, 1.5,
            16, 2,
          ],
          color: colors.styles.standard.industrial,
        },
        {
          id: 'railway_ferry_high',
          minzoom: 8,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['==', ['get', 'feature'], 'ferry'],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            8, 2,
            14, 2,
            16, 3,
          ],
          color: colors.styles.standard.ferry,
        },
        {
          id: 'railway_line_branch_high',
          minzoom: 8,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['all',
            ['==', ['get', 'feature'], 'rail'],
            ['==', ['get', 'usage'], 'branch'],
          ],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            8, 2,
            14, 2,
            16, 3,
          ],
          color: colors.styles.standard.branch,
        },
        {
          id: 'railway_line_main_high',
          minzoom: 8,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
          },
          filter: ['all',
            ['==', ['get', 'feature'], 'rail'],
            ['==', ['get', 'usage'], 'main'],
          ],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            8, 2,
            14, 2,
            16, 3,
          ],
          color: ['case',
            ['get', 'highspeed'], colors.styles.standard.highspeed,
            colors.styles.standard.main,
          ],
          hoverColor: ['case',
            ['get', 'highspeed'], colors.hover.alternative,
            colors.hover.main,
          ],
        },
      ],
    ),
  route,
  routeText,
  {
      id: 'railway_turntables_fill',
      type: 'fill',
      minzoom: 10,
      source: 'openrailwaymap_standard',
      'source-layer': 'standard_railway_turntables',
      paint: {
        'fill-color': colors.styles.standard.turntable.fill,
      },
      layout: {
        'visibility': ['case',
          ['<', ['global-state', 'date'], defaultDate], 'none',
          'visible',
        ],
      },
    },
  {
      id: 'railway_turntables_casing',
      type: 'line',
      minzoom: 15,
      source: 'openrailwaymap_standard',
      'source-layer': 'standard_railway_turntables',
      paint: {
        'line-color': colors.styles.standard.turntable.casing,
        'line-width': turntable_casing_width,
      },
      layout: {
        'visibility': ['case',
          ['<', ['global-state', 'date'], defaultDate], 'none',
          'visible',
        ],
      },
    },
  routeStops,
  searchResults
]
