import * as shared from '../shared.mjs'
import { sources } from './sources.mjs'
const { signals_railway_line, loading_gauges, track_classes, knownStyles, defaultDate, themeSwitch, colors, font, turntable_casing_width, trainProtectionColor, railway_casing_add, bridge_casing_add, abandoned_dasharray, disused_dasharray, razed_dasharray, construction_dasharray, proposed_dasharray, present_dasharray, train_protection_construction_dasharray, turboColorMap, speedColor, speedHoverColor, electrification_construction_dashes, electrification_proposed_dashes, color_no, color_delectrified, color_lt750v_dc, color_750v_dc, color_gt750v_lt1kv_dc, color_1kv_dc, color_gt1kv_lt1500v_dc, color_1500v_dc, color_gt1500v_lt3kv_dc, color_3kv_dc, color_gt3kv_dc, color_lt15kv_ac, color_gte15kv_lt25kv_ac, color_gte25kv_ac, color_15kv_16_67hz, color_15kv_16_7hz, color_25kv_50hz, color_25kv_60hz, color_12kv_25hz, color_12_5kv_60hz, color_20kv_50hz, color_20kv_60hz, electrificationVoltageFrequencyColor, electrificationVoltageMaximumCurrentColor, electrificationPowerColor, gauge_construction_dashes, dual_construction_dashes, multi_construction_dashes, gauge_dual_gauge_dashes, gauge_multi_gauge_dashes, color_gauge_0064, color_gauge_0089, color_gauge_0127, color_gauge_0184, color_gauge_0190, color_gauge_0260, color_gauge_0381, color_gauge_0500, color_gauge_0597, color_gauge_0600, color_gauge_0610, color_gauge_0700, color_gauge_0750, color_gauge_0760, color_gauge_0762, color_gauge_0785, color_gauge_0800, color_gauge_0891, color_gauge_0900, color_gauge_0914, color_gauge_0950, color_gauge_1000, color_gauge_1009, color_gauge_1050, color_gauge_1067, color_gauge_1100, color_gauge_1200, color_gauge_1372, color_gauge_1422, color_gauge_1432, color_gauge_1435, color_gauge_1440, color_gauge_1445, color_gauge_1450, color_gauge_1458, color_gauge_1495, color_gauge_1520, color_gauge_1522, color_gauge_1524, color_gauge_1581, color_gauge_1588, color_gauge_1600, color_gauge_1668, color_gauge_1676, color_gauge_1700, color_gauge_1800, color_gauge_1880, color_gauge_2000, color_gauge_miniature, color_gauge_monorail, color_gauge_broad, color_gauge_narrow, color_gauge_standard, color_gauge_unknown, gaugeColor, loadingGaugeFillColor, trackClassFillColor, searchResults, railwayLine, historicalRailwayLine, railwayKmText, preferredDirectionLayer, imageLayerWithOutline, hillshade, route, routeText, routeStops, DATA_MAX_ZOOM, capSourcesForDataMaxZoom, capLayersForDataMaxZoom, makeStyle } = shared
export const trackLayers = [
    hillshade,
    ...railwayLine(
      ['match', ['global-state', 'trackRailwayLine'],
        'gauge', ['coalesce', ['get', 'gauge_label'], ''],
        'loadingGauge', ['coalesce', ['get', 'loading_gauge'], ''],
        'trackClass', ['coalesce', ['get', 'track_class'], ''],
        '',
      ],
      [
        {
          id: 'railway_line_low',
          minzoom: 0,
          maxzoom: 7,
          source: 'track_railway_line_low',
          sourceLayer: 'track_railway_line_low',
          states: {
            present: undefined,
          },
          filter: ['!=', ['get', 'feature'], 'ferry'],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            0, 0.5,
            7, 2,
          ],
          color: ['match', ['global-state', 'trackRailwayLine'],
            'loadingGauge', loadingGaugeFillColor,
            'trackClass', trackClassFillColor,
            gaugeColor('gauge0', 'gaugeint0'),
          ],
        },
        {
          id: 'railway_line_med',
          minzoom: 7,
          maxzoom: 8,
          source: 'openrailwaymap_low',
          states: {
            present: undefined,
          },
          filter: ['!=', ['get', 'feature'], 'ferry'],
          width: 2,
          color: ['match', ['global-state', 'trackRailwayLine'],
            'loadingGauge', loadingGaugeFillColor,
            'trackClass', trackClassFillColor,
            gaugeColor('gauge0', 'gaugeint0'),
          ],
        },
        {
          id: 'railway_line_high_gauge',
          minzoom: 8,
          source: 'high',
          states: {
            present: undefined,
            construction: gauge_construction_dashes,
            disused: disused_dasharray,
            preserved: disused_dasharray,
          },
          filter: ['!=', ['get', 'feature'], 'ferry'],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            14, 2,
            16, 3,
          ],
          color: gaugeColor('gauge0', 'gaugeint0'),
          visibility: ['==', ['global-state', 'trackRailwayLine'], 'gauge'],
        },
        {
          id: 'railway_line_high_dual_gauge',
          minzoom: 8,
          source: 'high',
          states: {
            present: gauge_dual_gauge_dashes,
            construction: dual_construction_dashes,
          },
          filter: ['all',
            ['!=', ['get', 'feature'], 'ferry'],
            ['!=', ['get', 'gauge1'], null],
          ],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            14, 2,
            16, 3,
          ],
          color: gaugeColor('gauge1', 'gaugeint1'),
          visibility: ['==', ['global-state', 'trackRailwayLine'], 'gauge'],
        },
        {
          id: 'railway_line_high_multi_gauge',
          minzoom: 8,
          source: 'high',
          states: {
            present: gauge_multi_gauge_dashes,
            construction: multi_construction_dashes,
          },
          filter: ['all',
            ['!=', ['get', 'feature'], 'ferry'],
            ['!=', ['get', 'gauge2'], null],
          ],
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            14, 2,
            16, 3,
          ],
          color: gaugeColor('gauge2', 'gaugeint2'),
          visibility: ['==', ['global-state', 'trackRailwayLine'], 'gauge'],
        },
        {
          id: 'railway_line_high',
          minzoom: 8,
          source: 'high',
          states: {
            present: undefined,
            construction: construction_dasharray,
            proposed: proposed_dasharray,
            disused: disused_dasharray,
            preserved: disused_dasharray,
          },
          width: ["interpolate", ["exponential", 1.2], ["zoom"],
            14, 2,
            16, 3,
          ],
          color: ['match', ['global-state', 'trackRailwayLine'],
            'loadingGauge', loadingGaugeFillColor,
            'trackClass', trackClassFillColor,
            'gray',
          ],
          visibility: ['!=', ['global-state', 'trackRailwayLine'], 'gauge'],
        },
      ],
    ),
    route,
    routeText,
    routeStops,
    searchResults,
  ]
